---

- name: install ansible tower
  hosts: all
  become: yes
  roles:
  - oatakan.rhn
  - linux-common
  - role: ansible-tower
    tower_pass: "{{ lookup('env', 'TOWER_PASSWORD') }}"
  - tower-post-install