---

- name: install ansible tower
  hosts: all
  become: yes
  pre_tasks:
    - name: add hosts to tower group
      add_host:
        name: "{{ inventory_hostname }}"
        ansible_host: "{{ hostvars[inventory_hostname].ansible_host }}"
        ansible_port: "{{ hostvars[inventory_hostname].ansible_port }}"
        groups: tower
  roles:
  - ansible-role-rhn
  - linux-common
  - role: ansible-tower
    tower_pass: "{{ lookup('env', 'TOWER_PASSWORD') }}"
  - tower-post-install