---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    rhn_token_api_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    rhn_sub_allocation_url: https://api.access.redhat.com/management/v1/allocations
    rhn_sub_allocation_name: my_org_manifest
    rhn_token_client_id: rhsm-api # rhsm-api or cloud-services
  tasks:
    - name: generate refresh token
      ansible.builtin.uri:
        url: "{{ rhn_token_api_url }}"
        method: POST
        body_format: form-urlencoded
        body:
          grant_type: refresh_token
          client_id: "{{ rhn_token_client_id }}"
          refresh_token: "{{ rhn_api_offline_token }}"
        return_content: true
      register: rhn_api_refresh_token

    - name: get subscription list
      ansible.builtin.uri:
        url: "{{ rhn_sub_allocation_url }}"
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ rhn_api_refresh_token.json.access_token }}"
        return_content: true
      register: rh_sub_allocation_list
      when: rhn_token_client_id == "rhsm-api"