---
- hosts: tower:instance_group_*
  become: yes
  roles:
    - tower-harden
    - tower-post-install

- hosts: tower:instance_group_*
  become: no
  vars:
    app_name: tower_clustered
    role_name: tower_elb
  tasks:
    - include_role:
        name: ec2_elb_provision
      when: hosted_zone_domain_name is defined