---
- hosts: tower:instance_group_*
  become: yes
  roles:
    - tower-post-install

- hosts: tower:instance_group_*
  become: no
  vars:
    app_name: tower_clustered
    role_name: tower_elb
  tasks:
    - include_role:
        name: ec2_elb_provision
      when: hosted_zone_domain_name is defined

- name: test tower
  hosts: tower:instance_group_*
  gather_facts: no
  become: no
  tasks:
    - name: testing connection to tower
      tower_job_list:
        tower_host: "tower.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
        tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
        tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
      register: testing_jobs
      until: testing_jobs is success
      delay: 3
      retries: 300
      delegate_to: localhost
      run_once: yes
      when: hosted_zone_domain_name is defined