---

- name: Remove VM
  hosts: all
  gather_facts: False
  connection: local
  become: no
  vars_files:
    - node-config\tower-nodes-kubevirt.yml

  roles:
    - role: ansible-role-kubevirt
      role_action: deprovision
      delegate_to: localhost
      run_once: yes