---
- hosts: tower:database
  become: yes
  vars:
    postgresql_databases:
      - name: "{{ pg_database }}"
    postgresql_users:
      - name: "{{ pg_username }}"
        password: "{{ pg_password }}"
  roles:
    - oatakan.rhn
    - common
#    - geerlingguy.postgresql