- hosts: localhost
  become: no
  gather_facts: no
  roles:
    - ec2-find-amis

- hosts: localhost
  become: no
  gather_facts: no
  vars:
    ec2_tower_instance_ami_type: rhel8
  vars_files:
    - node-config/tower-nodes-ec2-{{ ec2_region }}.yml
  roles:
    - ansible-role-ec2