---

- name: post license key
  uri:
    url: http://localhost/api/v2/config/
    method: POST
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    body: "{{ tower_license }}"
    body_format: json
    validate_certs: False
    force_basic_auth: yes
  ignore_errors: True
  when: tower_license is defined

- name: Delete demo inventory
  uri:
    url:  http://localhost/api/v2/inventories/1/
    method: DELETE
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    validate_certs: False
    force_basic_auth: yes
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 400
      - 404
  register: response
  changed_when: response.status == 204

- name: Delete demo project
  uri:
    url:  http://localhost/api/v2/projects/4/
    method: DELETE
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    validate_certs: False
    force_basic_auth: yes
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 400
      - 404
  register: response
  changed_when: response.status == 204

- name: Delete demo template
  uri:
    url:  http://localhost/api/v2/job_templates/5/
    method: DELETE
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    validate_certs: False
    force_basic_auth: yes
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 400
      - 404
  register: response
  changed_when: response.status == 204

- name: Delete demo credential
  uri:
    url:  http://localhost/api/v2/credentials/1/
    method: DELETE
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    validate_certs: False
    force_basic_auth: yes
    status_code:
      - 200
      - 201
      - 202
      - 204
      - 400
      - 404
  register: response
  changed_when: response.status == 204