---

- name: post license key
  uri:
    url: "{{ tower_local_api_url }}/config/"
    method: POST
    user: "{{ tower_username }}"
    password: "{{ tower_password }}"
    body: "{{ tower_license }}"
    body_format: json
    validate_certs: False
    force_basic_auth: yes
  ignore_errors: True
  when: not use_manifest
  run_once: yes

- include_tasks: manifest.yml
  when: use_manifest

- block:
    - include_tasks: remove_demo.yml
  rescue:
    - include_tasks: remove_demo_api.yml