---

- name: install epel
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  register: install_epel
  until: '"error" not in install_epel'
  retries: 5
  delay: 10
  when: ansible_distribution_major_version|int < 8

- name: install packages needed
  yum:
    name: "{{ yum_packages }}"
    state: latest
  when: ansible_distribution_major_version|int < 8

- name: install pip packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version|default(omit) }}"
    virtualenv_command: /var/lib/awx/venv/ansible/bin/activate
    extra_args: --upgrade
    state: latest
  loop: "{{ pip_packages }}"

#- name: upgrade requests-credssp
#  command: /var/lib/awx/venv/ansible/bin/pip install requests-credssp --upgrade
#  ignore_errors: yes

- include_tasks: configure.yml
  when:
    - tower_username is defined
    - tower_password is defined
