---

- name: install epel
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  register: install_epel
  until: '"error" not in install_epel'
  retries: 5
  delay: 10

- name: install packages needed
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ yum_packages }}"

- name: install pip packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version|default(omit) }}"
    virtualenv_command: /var/lib/awx/venv/ansible/bin/activate
  with_items: "{{ pip_packages }}"
