---

#### REMOVE BUILT-IN DEMO CONTENT
- name: delete demo job template
  tower_job_template:
    name: "Demo Job Template"
    job_type: "run"
    project: "Demo Project"
    playbook: "hello_world.yml"
    state: absent
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    tower_host: localhost
    tower_verify_ssl: false

- name: remove demo credential
  tower_credential:
    username: admin
    name: "Demo Credential"
    kind: ssh
    state: absent
    organization: ""
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    tower_host: localhost
    tower_verify_ssl: false

- name: remove demo inventory
  tower_inventory:
    name: "Demo Inventory"
    organization: "Default"
    state: absent
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    tower_host: localhost
    tower_verify_ssl: false

- name: remove built-in tower project
  tower_project:
    name: "Demo Project"
    organization: "Default"
    scm_type: git
    state: absent
    tower_username: "{{ tower_username }}"
    tower_password: "{{ tower_password }}"
    tower_host: localhost
    tower_verify_ssl: false