---

- name: find ami id for rhel 7
  ec2_ami_info:
    owners: 309956199498
    filters:
      name: "{{ ec2_image_names['rhel7'] }}"
    region: "{{ ec2_region }}"
  register: rhel7_ami_find

- name: find ami id for rhel 8
  ec2_ami_info:
    owners: 309956199498
    filters:
      name: "{{ ec2_image_names['rhel8'] }}"
    region: "{{ ec2_region }}"
  register: rhel8_ami_find

- name: find ami id for centos 7
  ec2_ami_info:
    owners: aws-marketplace
    filters:
      name: "{{ ec2_image_names['centos7'] }}"
    region: "{{ ec2_region }}"
  register: centos7_ami_find

- name: find ami id for centos 8
  ec2_ami_info:
    owners: aws-marketplace
    filters:
      name: "{{ ec2_image_names['centos8'] }}"
    region: "{{ ec2_region }}"
  register: centos8_ami_find

- name: set ami ids
  set_fact:
    ec2_ami_ids:
      rhel7: "{{ rhel7_ami_find.images[-1].image_id | default('') }}"
      rhel8: "{{ rhel8_ami_find.images[-1].image_id | default('') }}"
      centos7: "{{ centos7_ami_find.images[-1].image_id | default('') }}"
      centos8: "{{ centos8_ami_find.images[-1].image_id | default('') }}"

- debug:
    var: ec2_ami_ids
  when: ec2_ami_ids is defined
