---

- name: Add EPEL repo
  yum_repository:
    name: epel
    description: EPEL for Enterprise Linux 7
    baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/
    enabled: yes
    gpgcheck: no
  when: ansible_distribution_major_version|int < 8

- name: Add Epel repo
  yum_repository:
    name: epel
    description: EPEL for Enterprise Linux 8
    baseurl: https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/
    enabled: yes
    gpgcheck: no
  when: ansible_distribution_major_version|int == 8