---
- name: remove router ELB DNS entry
  route53:
    state: absent
    overwrite: yes
    zone: "{{ hosted_zone_domain_name }}"
    record: "{{ subdomain }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
    type: A
    value: "{{ elb_lb.elb.dns_name }}"
  delegate_to: 127.0.0.1
  run_once: yes

- name: remove ec2 elb lb
  ec2_elb_lb:
    name: "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-lb"
    state: absent
    region: "{{ ec2_region }}"
  delegate_to: 127.0.0.1
  run_once: yes

- name: remove ec2 security group
  ec2_group:
    name: "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-sg"
    description: allow http and https
    region: "{{ ec2_region }}"
    state: absent
  delegate_to: 127.0.0.1
  run_once: yes

