---
- name: get record for router ELB DNS Entry
  route53:
    command: get
    zone: "{{ hosted_zone_domain_name }}"
    record: "{{ subdomain}}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
    type: A
  register: routerelbrec
  when: hosted_zone_domain_name is defined and ec2_name_prefix is defined

- name: delete Router ELB DNS Entry if it doesn't exist
  route53:
    state: absent
    zone: "{{ hosted_zone_domain_name }}"
    record: "{{ subdomain}}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
    type: A
    value: "{{ routerelbrec.set.value }}"
    alias: True
    alias_hosted_zone_id: "{{ routerelbrec.set.alias_hosted_zone_id }}"
  when: routerelbrec.set is defined and "{} != routerelbrec.set"

- name: remove ec2 elb lb
  ec2_elb_lb:
    name: "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-lb"
    state: absent
    region: "{{ ec2_region }}"
    wait: yes
    wait_timeout: 600

- name: remove ec2 security group
  ec2_group:
    name: "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-sg"
    description: allow http and https
    region: "{{ ec2_region }}"
    state: absent

