---
- name: Initialize instance groups for host
  set_fact:
    awx_instance_groups: []
  run_once: yes

- debug:
    msg: "{{ hostvars[item].group_names }}"
  with_items: "{{ play_hosts }}"
  run_once: yes

- name: Determine instance groups for host
  set_fact:
    awx_instance_groups: "{{ awx_instance_groups }} + [ '{{ hostvars[item].group_names[0]|regex_replace('^instance_group_','') }}' ]"
  with_items: "{{ play_hosts }}"
  when: hostvars[item].group_names[0] | match("(^tower|^instance_group_.+)$")
  run_once: yes

- debug:
    var: awx_instance_groups
  run_once: yes

- include: elb.yml instance_group='{{ include_item }}'
  with_items: "{{ awx_instance_groups }}"
  loop_control:
    loop_var: include_item
  run_once: yes