---
- name: Initialize instance groups for host
  set_fact:
    awx_instance_groups: []
  run_once: yes

- name: debug hosts
  debug:
    var: "{{ groups.keys() }}"
  run_once: yes

- name: Determine instance groups for host
  set_fact:
    awx_instance_groups: "{{ awx_instance_groups }} + [ '{{ item }}' ]"
  with_items:
    - "{{ groups.keys() }}"
  when: item is match("(^tower|^instance_group_.+)$")
  run_once: yes

- debug:
    var: awx_instance_groups
  run_once: yes

- include: elb.yml instance_group='{{ include_item }}'
  with_items: "{{ awx_instance_groups }}"
  loop_control:
    loop_var: include_item
  run_once: yes
  when: groups[include_item]|length > 0