---
- name: set targets from list
  set_fact:
    instance_ids: "{{ instance_ids|default([]) + [ {'id': hostvars[item].ec2_id, 'region': hostvars[item].ec2_region } ] }}"
  with_items: "{{ play_hosts }}"
  run_once: yes

- name: ceate ec2 security group
  ec2_group:
    name: "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-sg"
    description: allow http and https
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_vpc_id }}"
    rules:
      - proto: udp
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
      #- proto: tcp
      #  from_port: 80
      #  to_port: 80
      #  cidr_ip: 0.0.0.0/0
      #- proto: tcp
      #  from_port: 443
      #  to_port: 443
      #  cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
    tags:
      name: "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-sg"
      role: "{{ role_name }}"
      app: "{{ app_name }}"
  delegate_to: 127.0.0.1
  run_once: yes

- name: provision a new ec2 elb lb
  ec2_elb_lb:
    name: "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-lb"
    state: present
    region: "{{ ec2_region }}"
    #instance_ids: "{{ instance_ids | map(attribute='id') | list }}"
    security_group_names:
      - "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-sg"
    subnets:
      - "{{ ec2_vpc_subnet_id }}"
    purge_instance_ids: true
    cross_az_load_balancing: yes
    listeners:
      - protocol: tcp
        load_balancer_port: 80
        instance_port: 80
      - protocol: tcp
        load_balancer_port: 443
        instance_port: 443
        #ssl_certificate_id: "{{ ec2_cert_id }}"
    health_check:
      ping_protocol: tcp # options are http, https, ssl, tcp
      ping_port: 443
      #ping_path: "/index.html" # not required for tcp or ssl
      response_timeout: 5 # seconds
      interval: 10 # seconds
      unhealthy_threshold: 2
      healthy_threshold: 2
    tags:
      name: "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-lb"
      role: "{{ role_name }}"
      app: "{{ app_name }}"
  register: elb_lb
  delegate_to: 127.0.0.1
  run_once: yes

- name: add instances to elb
  ec2_elb:
    state: present
    ec2_elbs:
      - "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-lb"
    region: "{{ item.region }}"
    instance_id: "{{ item.id }}"
  with_items: "{{ instance_ids }}"
  delegate_to: 127.0.0.1
  run_once: yes

- name: create router ELB DNS rntry if it doesn't exist
  route53:
    state: present
    overwrite: yes
    zone: "{{ hosted_zone_domain_name }}"
    record: "{{ subdomain }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
    type: A
    value: "{{ elb_lb.elb.dns_name }}"
    alias: True
    alias_hosted_zone_id: "{{ elb_lb.elb.hosted_zone_id }}"
  delegate_to: 127.0.0.1
  run_once: yes

- name: output url
  debug:
    msg: 'application is available at https://{{ subdomain }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}/'