---
- name: set targets from list
  set_fact:
    instance_ids: "{{ instance_ids|default([]) + [ {'id': hostvars[item].ec2_id, 'region': hostvars[item].ec2_region } ] }}"
  with_items: "{{ play_hosts }}"
  run_once: yes

- name: ceate ec2 security group
  ec2_group:
    name: "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-sg"
    description: allow http and https
    region: "{{ ec2_region }}"
    vpc_id: "{{ ec2_vpc_id }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
    tags:
      name: "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-sg"
      role: "{{ role_name }}"
      app: "{{ app_name }}"
  delegate_to: 127.0.0.1
  run_once: yes

- name: provision a new ec2 elb lb
  ec2_elb_lb:
    name: "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-lb"
    state: present
    region: "{{ ec2_region }}"
    #instance_ids: "{{ instance_ids | map(attribute='id') | list }}"
    security_group_names:
      - "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-sg"
    subnets:
      - "{{ ec2_vpc_subnet_id }}"
    purge_instance_ids: true
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
        proxy_protocol: True
      - protocol: https
        load_balancer_port: 443
        instance_port: 443
        proxy_protocol: True
        ssl_certificate_id: "{{ ec2_cert_id }}"
    tags:
      name: "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-lb"
      role: "{{ role_name }}"
      app: "{{ app_name }}"
  register: elb_lb
  delegate_to: 127.0.0.1
  run_once: yes

- name: add instances to elb
  ec2_elb:
    state: present
    ec2_elbs:
      - "{{ ec2_name_prefix }}-{{ app_name | replace('_','-') }}-elb-lb"
    region: "{{ item.region }}"
    instance_id: "{{ item.id }}"
  with_items: "{{ instance_ids }}"
  delegate_to: 127.0.0.1
  run_once: yes

- debug:
    var: elb_lb
  run_once: yes

- name: Get record for router ELB DNS Entry
  route53:
    command: get
    zone: "{{ hosted_zone_domain_name }}"
    record: "{{ subdomain }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
    type: A
  register: routerelbrec

- name: create router ELB DNS rntry if it doesn't exist
  route53:
    state: present
    zone: "{{ hosted_zone_domain_name }}"
    record: "{{ subdomain }}.{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}"
    type: A
    value: "{{ elb_lb.elb.dns_name }}"
    alias: True
    alias_hosted_zone_id: "{{ routerelb.elb.hosted_zone_id }}"
  delegate_to: 127.0.0.1
  run_once: yes