---
- name: Initialize instance groups for host
  set_fact:
    awx_instance_groups: []
  run_once: yes

- debug:
    msg: "{{ item }}"
  with_items:
    - "{{ groups }}"
  when: item | match("(^tower|^instance_group_.+)$")
  run_once: yes

- name: Determine instance groups for host
  set_fact:
    awx_instance_groups: "{{ awx_instance_groups }} + [ '{{ item|regex_replace('^instance_group_','') }}' ]"
  with_items:
    - "{{ group }}"
  when: item | match("(^tower|^instance_group_.+)$")
  run_once: yes

- debug:
    var: awx_instance_groups
  run_once: yes

- include: elb.yml instance_group='{{ include_item }}'
  with_items: "{{ awx_instance_groups }}"
  loop_control:
    loop_var: include_item
  run_once: yes